name: WEB Tests
on:
  pull_request:
    branches:
      - '**'
jobs:
  web-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Google Chrome
        run: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb
      - name: Install Google Chromedriver
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
      - name: Install and Start Selenium Webdriver
        run: |
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-3.141.59/selenium-server-standalone-3.141.59.jar
          java -jar selenium-server-standalone-3.141.59.jar
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Install dependencies
        run: mvn clean install -DskipTests
      - name: Run WEB tests
        run: mvn test -Dtest=WebSampleTest
